#!/bin/bash
# Auto-generiertes Cleanup-Script
# Generiert am: 2025-07-11 16:23:33

echo "🧹 PROJEKT-BEREINIGUNG"
echo "===================="

# Farben
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Sicherheitsabfrage
echo -e "${YELLOW}⚠️  WARNUNG: Dieses Script wird Dateien löschen!${NC}"
echo -e "Bitte überprüfen Sie cleanup_review.txt für Details."
read -p "Fortfahren? (j/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Jj]$ ]]; then
    echo "Abgebrochen."
    exit 1
fi

# Erstelle Trash-Verzeichnis
TRASH_DIR=".trash_$(date +%Y%m%d_%H%M%S)"
mkdir -p "$TRASH_DIR"
echo -e "${GREEN}Trash-Verzeichnis erstellt: $TRASH_DIR${NC}"


# Backup-Dateien
echo -e "\n${YELLOW}Backup-Dateien verschieben...$${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/.env.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ .env.backup${NC}" || echo -e "${RED}✗ .env.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/check_system_extended.py.bak" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ check_system_extended.py.bak${NC}" || echo -e "${RED}✗ check_system_extended.py.bak${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/exchange.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ exchange.py.backup${NC}" || echo -e "${RED}✗ exchange.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/__init__.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py.backup${NC}" || echo -e "${RED}✗ __init__.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/exchange.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ exchange.py.backup${NC}" || echo -e "${RED}✗ exchange.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/trading_bot.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ trading_bot.py.backup${NC}" || echo -e "${RED}✗ trading_bot.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/trading_bot.py.backup_final" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ trading_bot.py.backup_final${NC}" || echo -e "${RED}✗ trading_bot.py.backup_final${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/strategies/__init__.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py.backup${NC}" || echo -e "${RED}✗ __init__.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/__init__.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py.backup${NC}" || echo -e "${RED}✗ __init__.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/exchange.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ exchange.py.backup${NC}" || echo -e "${RED}✗ exchange.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/trading_bot.py.backup_final" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ trading_bot.py.backup_final${NC}" || echo -e "${RED}✗ trading_bot.py.backup_final${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/__init__.py.backup" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py.backup${NC}" || echo -e "${RED}✗ __init__.py.backup${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backups/main.py.backup.20250710_233355" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ main.py.backup.20250710_233355${NC}" || echo -e "${RED}✗ main.py.backup.20250710_233355${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backups/main.py.backup.20250710_233922" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ main.py.backup.20250710_233922${NC}" || echo -e "${RED}✗ main.py.backup.20250710_233922${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backups/main.py.backup.20250710_233142" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ main.py.backup.20250710_233142${NC}" || echo -e "${RED}✗ main.py.backup.20250710_233142${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backups/main.py.backup.20250710_233702" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ main.py.backup.20250710_233702${NC}" || echo -e "${RED}✗ main.py.backup.20250710_233702${NC}"

# Temporäre Dateien
echo -e "\n${YELLOW}Temporäre Dateien verschieben...$${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/test_setup.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ test_setup.py${NC}" || echo -e "${RED}✗ test_setup.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/debug_imports.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ debug_imports.py${NC}" || echo -e "${RED}✗ debug_imports.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/.DS_Store" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ .DS_Store${NC}" || echo -e "${RED}✗ .DS_Store${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_trading_bot_sustainable.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_trading_bot_sustainable.py${NC}" || echo -e "${RED}✗ fix_trading_bot_sustainable.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_exchange_sustainable.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_exchange_sustainable.py${NC}" || echo -e "${RED}✗ fix_exchange_sustainable.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_logger_problem.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_logger_problem.py${NC}" || echo -e "${RED}✗ fix_logger_problem.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/ml_backtest.log" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_backtest.log${NC}" || echo -e "${RED}✗ ml_backtest.log${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_files.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_files.py${NC}" || echo -e "${RED}✗ fix_files.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/test_bot.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ test_bot.py${NC}" || echo -e "${RED}✗ test_bot.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/logs/test_check.log" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ test_check.log${NC}" || echo -e "${RED}✗ test_check.log${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/logs/trading_bot.log" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ trading_bot.log${NC}" || echo -e "${RED}✗ trading_bot.log${NC}"

# Test-Artefakte
echo -e "\n${YELLOW}Test-Artefakte verschieben...$${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/paper_trading_wrapper.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ paper_trading_wrapper.py${NC}" || echo -e "${RED}✗ paper_trading_wrapper.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/run_paper_trading.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ run_paper_trading.py${NC}" || echo -e "${RED}✗ run_paper_trading.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/timestamp_patch.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ timestamp_patch.py${NC}" || echo -e "${RED}✗ timestamp_patch.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/debug_imports.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ debug_imports.py${NC}" || echo -e "${RED}✗ debug_imports.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/test_bot.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ test_bot.py${NC}" || echo -e "${RED}✗ test_bot.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/start_autopilot.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ start_autopilot.py${NC}" || echo -e "${RED}✗ start_autopilot.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/run_all_strategies.sh" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ run_all_strategies.sh${NC}" || echo -e "${RED}✗ run_all_strategies.sh${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_everything.sh" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_everything.sh${NC}" || echo -e "${RED}✗ fix_everything.sh${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/fix_imports.sh" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ fix_imports.sh${NC}" || echo -e "${RED}✗ fix_imports.sh${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/LAZY_MILLIONAIRE_STACK_SETUP.sh" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ LAZY_MILLIONAIRE_STACK_SETUP.sh${NC}" || echo -e "${RED}✗ LAZY_MILLIONAIRE_STACK_SETUP.sh${NC}"

# Alte Configs
echo -e "\n${YELLOW}Alte Configs verschieben...$${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/config/backtest_config.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ backtest_config.json${NC}" || echo -e "${RED}✗ backtest_config.json${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/config/profiles/copy_trading.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ copy_trading.json${NC}" || echo -e "${RED}✗ copy_trading.json${NC}"

# Veraltete Strategien
echo -e "\n${YELLOW}Veraltete Strategien verschieben...$${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/strategies/advanced.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ advanced.py${NC}" || echo -e "${RED}✗ advanced.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/strategies/regime_adaptive.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ regime_adaptive.py${NC}" || echo -e "${RED}✗ regime_adaptive.py${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/strategies/DeFi_yield.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ DeFi_yield.py${NC}" || echo -e "${RED}✗ DeFi_yield.py${NC}"

# Duplikate
echo -e "\n${YELLOW}Duplikate verschieben...${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/security.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ security.py (Duplikat von risk.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/security/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/performance/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/risk/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/data_collector.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ data_collector.py (Duplikat von data_collector.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/risk.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ risk.py (Duplikat von security.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/backtest_engine.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ backtest_engine.py (Duplikat von backtest_engine.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/enhanced_backtesting.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ enhanced_backtesting.py (Duplikat von enhanced_backtesting.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/position.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ position.py (Duplikat von position.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/order_manager.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ order_manager.py (Duplikat von order_manager.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/security.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ security.py (Duplikat von risk.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/performance.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ performance.py (Duplikat von performance.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/risk_manager.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ risk_manager.py (Duplikat von risk_manager.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/ml_enhanced_backtesting.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_enhanced_backtesting.py (Duplikat von ml_enhanced_backtesting.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/security/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/performance/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/core/performance/engine.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ engine.py (Duplikat von engine.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/core/risk/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/advanced/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von on_chain.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/analysis/technical.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ technical.py (Duplikat von on_chain.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/analysis/on_chain.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ on_chain.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/analysis/machine_learning.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ machine_learning.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/analysis/social_media.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ social_media.py (Duplikat von __init__.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/analysis/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/config/api_keys..py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ api_keys..py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/config/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/config/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/advanced.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ advanced.py (Duplikat von advanced.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/strategy_base.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ strategy_base.py (Duplikat von strategy_base.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/ml_strategy.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_strategy.py (Duplikat von ml_strategy.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/arbitrage.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ arbitrage.py (Duplikat von arbitrage.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/regime_adaptive.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ regime_adaptive.py (Duplikat von regime_adaptive.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/copy_trading.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ copy_trading.py (Duplikat von copy_trading.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/DeFi_yield.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ DeFi_yield.py (Duplikat von DeFi_yield.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/grid_trading.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ grid_trading.py (Duplikat von grid_trading.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/mean_reversion.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ mean_reversion.py (Duplikat von mean_reversion.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/liquidation.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ liquidation.py (Duplikat von liquidation.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/strategies/advanced/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/advanced/hybird_ml.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ hybird_ml.py (Duplikat von hybird_ml.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/utils/visualization.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ visualization.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/utils/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/utils/helpers.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ helpers.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/ml_components/model_storage.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ model_storage.py (Duplikat von model_monitor.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/api_keys..py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ api_keys..py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/backtest_config.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ backtest_config.json (Duplikat von backtest_config.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/settings.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ settings.py (Duplikat von settings.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/examples/momentum_standard.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ momentum_standard.json (Duplikat von momentum_standard.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/examples/config/examples/momentum_standard.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ momentum_standard.json (Duplikat von momentum_standard.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/examples/config/examples/config_examples.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ config_examples.json (Duplikat von config_examples.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/liquidation.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ liquidation.json (Duplikat von liquidation.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/arbitrage.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ arbitrage.json (Duplikat von arbitrage.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/autopilot.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ autopilot.json (Duplikat von autopilot.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/copy_trading.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ copy_trading.json (Duplikat von copy_trading.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/grid.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ grid.json (Duplikat von grid.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/default.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ default.json (Duplikat von default.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/config/profiles/defi.json" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ defi.json (Duplikat von defi.json)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/advanced.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ advanced.py (Duplikat von advanced.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/ml_strategy.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_strategy.py (Duplikat von ml_strategy.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/regime_adaptive.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ regime_adaptive.py (Duplikat von regime_adaptive.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/mean_reversion.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ mean_reversion.py (Duplikat von mean_reversion.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/momentum.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ momentum.py (Duplikat von momentum.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/advanced/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_20250711_144916/strategies/advanced/hybird_ml.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ hybird_ml.py (Duplikat von hybird_ml.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/data_sources/data_sources/coingecko_source.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ coingecko_source.py (Duplikat von coingecko_source.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/data_sources/data_sources/base.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ base.py (Duplikat von base.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/main.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ main.py (Duplikat von main.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/data_collector.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ data_collector.py (Duplikat von data_collector.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/security.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ security.py (Duplikat von risk.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/backtest_engine.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ backtest_engine.py (Duplikat von backtest_engine.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/enhanced_backtesting.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ enhanced_backtesting.py (Duplikat von enhanced_backtesting.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/position.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ position.py (Duplikat von position.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/order_manager.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ order_manager.py (Duplikat von order_manager.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/risk.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ risk.py (Duplikat von risk.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/performance.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ performance.py (Duplikat von performance.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/risk_manager.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ risk_manager.py (Duplikat von risk_manager.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/ml_enhanced_backtesting.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_enhanced_backtesting.py (Duplikat von ml_enhanced_backtesting.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/security/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/performance/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/performance/engine.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ engine.py (Duplikat von engine.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/core/risk/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/advanced.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ advanced.py (Duplikat von advanced.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/strategy_base.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ strategy_base.py (Duplikat von strategy_base.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_imports_20250711_145555/strategies/autopilot.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ autopilot.py (Duplikat von autopilot.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/ml_strategy.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ ml_strategy.py (Duplikat von ml_strategy.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/arbitrage.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ arbitrage.py (Duplikat von arbitrage.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/regime_adaptive.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ regime_adaptive.py (Duplikat von regime_adaptive.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/copy_trading.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ copy_trading.py (Duplikat von copy_trading.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/DeFi_yield.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ DeFi_yield.py (Duplikat von DeFi_yield.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/grid_trading.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ grid_trading.py (Duplikat von grid_trading.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/init.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ init.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/mean_reversion.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ mean_reversion.py (Duplikat von mean_reversion.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/liquidation.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ liquidation.py (Duplikat von liquidation.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/momentum.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ momentum.py (Duplikat von momentum.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/advanced/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/backup_final_20250711_152841/strategies/advanced/hybird_ml.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ hybird_ml.py (Duplikat von hybird_ml.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/services/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"
mv "/Users/jnb/PycharmProjects/altcoin_trading_bot/services/websocket/__init__.py" "$TRASH_DIR/" 2>/dev/null && echo -e "${GREEN}✓ __init__.py (Duplikat von init.py)${NC}"

# __pycache__ Verzeichnisse
echo -e "\n${YELLOW}__pycache__ Verzeichnisse löschen...${NC}"
find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null
echo -e "${GREEN}✓ __pycache__ Verzeichnisse gelöscht${NC}"

# .pyc Dateien
find . -name "*.pyc" -delete 2>/dev/null

echo -e "\n${GREEN}✅ Bereinigung abgeschlossen!${NC}"
echo -e "${YELLOW}Gelöschte Dateien befinden sich in: $TRASH_DIR${NC}"
echo -e "${YELLOW}Sie können das Verzeichnis mit 'rm -rf $TRASH_DIR' endgültig löschen.${NC}"
